// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCogDOsK-Ew4yWykVNKEEypttWVWMVOUqg',
    appId: '1:502303671561:web:8245328901694838f7ffd8',
    messagingSenderId: '502303671561',
    projectId: 'crudtutorial-65360',
    authDomain: 'crudtutorial-65360.firebaseapp.com',
    storageBucket: 'crudtutorial-65360.appspot.com',
    measurementId: 'G-NWRPDJRVL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-KUFL57X-9Sl3mFSDelzy0C-I1IPxsEQ',
    appId: '1:502303671561:android:6934724c7056eb8ef7ffd8',
    messagingSenderId: '502303671561',
    projectId: 'crudtutorial-65360',
    storageBucket: 'crudtutorial-65360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYrH6YsGEmbf4hrDALva75CxJ6iKda1j0',
    appId: '1:502303671561:ios:4610c5bc73404a64f7ffd8',
    messagingSenderId: '502303671561',
    projectId: 'crudtutorial-65360',
    storageBucket: 'crudtutorial-65360.appspot.com',
    iosBundleId: 'com.example.crudThought',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYrH6YsGEmbf4hrDALva75CxJ6iKda1j0',
    appId: '1:502303671561:ios:4610c5bc73404a64f7ffd8',
    messagingSenderId: '502303671561',
    projectId: 'crudtutorial-65360',
    storageBucket: 'crudtutorial-65360.appspot.com',
    iosBundleId: 'com.example.crudThought',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCogDOsK-Ew4yWykVNKEEypttWVWMVOUqg',
    appId: '1:502303671561:web:d2834e6ccf5bcc55f7ffd8',
    messagingSenderId: '502303671561',
    projectId: 'crudtutorial-65360',
    authDomain: 'crudtutorial-65360.firebaseapp.com',
    storageBucket: 'crudtutorial-65360.appspot.com',
    measurementId: 'G-T5RWMTBSRN',
  );
}
